In [1]:
!pip install tensorflow


[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: pip install --upgrade pip


In [2]:
import tensorflow as tf
print(tf.__version__)

2.16.2


In [3]:
gpus = tf.config.list_physical_devices('GPU')
print("GPUs:", gpus)
print("Using:", "GPU" if gpus else "CPU")

GPUs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Using: GPU


In [4]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [14]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [15]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [16]:
voc_size=500

### One hot representation

In [17]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[469, 338, 37, 193], [469, 338, 37, 287], [469, 397, 37, 422], [418, 85, 20, 81, 315], [418, 85, 20, 81, 256], [138, 469, 170, 37, 150], [314, 455, 148, 81]]


### Word Embedding Represntation

In [19]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [22]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 469 338  37 193]
 [  0   0   0   0 469 338  37 287]
 [  0   0   0   0 469 397  37 422]
 [  0   0   0 418  85  20  81 315]
 [  0   0   0 418  85  20  81 256]
 [  0   0   0 138 469 170  37 150]
 [  0   0   0   0 314 455 148  81]]


In [23]:
## 10 feature dimesnions
dim=10


In [26]:
from tensorflow.keras.layers import Input
model=Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size,10))
model.compile('adam','mse')

In [27]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
embedded_docs[0]

array([  0,   0,   0,   0, 469, 338,  37, 193], dtype=int32)

In [33]:
model.predict(embedded_docs[0].reshape(1,sent_length))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step


array([[[ 0.03198469,  0.04164927, -0.03237364, -0.0041105 ,
         -0.01008124,  0.01154696, -0.04802188,  0.03898898,
          0.02859413,  0.0019183 ],
        [ 0.03198469,  0.04164927, -0.03237364, -0.0041105 ,
         -0.01008124,  0.01154696, -0.04802188,  0.03898898,
          0.02859413,  0.0019183 ],
        [ 0.03198469,  0.04164927, -0.03237364, -0.0041105 ,
         -0.01008124,  0.01154696, -0.04802188,  0.03898898,
          0.02859413,  0.0019183 ],
        [ 0.03198469,  0.04164927, -0.03237364, -0.0041105 ,
         -0.01008124,  0.01154696, -0.04802188,  0.03898898,
          0.02859413,  0.0019183 ],
        [-0.0346617 ,  0.01280737,  0.04282714, -0.01397728,
         -0.03318258, -0.0308032 ,  0.03532534, -0.03941114,
          0.03308198,  0.01224969],
        [ 0.00601041, -0.01086197, -0.04445435,  0.01781002,
         -0.02168404, -0.03870247, -0.01555075,  0.00340218,
         -0.01249545, -0.00554002],
        [ 0.02481195,  0.00746183, -0.02975829,  0.0

In [36]:
print(model.predict(embedded_docs).shape)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
(7, 8, 10)
